---
- name: Install Percona Repository
  yum: name={{ percona_repository }} state=present

- name: Install Percona Database
  yum: name={{ item }} state=present
  with_items:
  - Percona-Server-shared-57
  - Percona-Server-server-57
  - Percona-Server-client-57
  - MySQL-python
- name: Load default Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf

- name: Automatic load when boot
  service: name=mysqld state=started enabled=yes

- name: Be sure mysqld is running and enable
  service: name=mysqld state=running enabled=true

- name: Copy nginx configuration for wordpress
  template: src=cent.sh dest=/root/cent.sh

- name: Execute the script
  command: sudo sh /root/cent.sh
